# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# - script: |
#       curl -fsS https://tools.veracode.com/veracode-cli/install | sh
#       /home/vsts/work/1/s/veracode configure
#       Veracode_API_ID='$(VERACODE_API_ID)'
#       Veracode_API_ID='$(VERACODE_API_KEY)'
#       /home/vsts/work/1/s/veracode configure
#   displayName: 'Veracode cli'



- task: Bash@3
  displayName: tf Scanner
  inputs:
      targetType: inline
      script: |
          pwd
          export VERACODE_API_KEY_ID=9c42b4bd8abf978e9dc1667451778c58
          export VERACODE_API_KEY_SECRET=568e7bd345890259c3e869c8da3d42597b815e6a780c5d72ce76eaf3045a1736d80eb0ced53eb61956b3f0410546b2ac6e681829eaa3c9c621fcd722cee60b14
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          ./veracode scan --type directory --source '$(Build.SourcesDirectory)' --format table 2 >&1 | tee container-scan.json

# - task: CmdLine@2
#   inputs:
#     script: './veracode scan --type directory --source ./terraform-examples/ --format table'
#   displayName: 'Scan'
